// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::RoadDetails;
use super::parts::{GetRoadWorksInput, GetRoadWorksResponse, get_road_works_parts};
use serde::de;
/// Returns road works currently in progress or planned, together with event details and the responsible agency.
///
/// **Update freq**: 24 hours – whenever there are updates
pub fn encode_get_road_works(
    input: GetRoadWorksInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_road_works_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_road_works_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetRoadWorksResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<RoadDetails<S>>>(
                body, "value", None,
            )?;
            Ok(GetRoadWorksResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetRoadWorksResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
