// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::RoadDetails;
/// Returns road works currently in progress or planned, together with event details and the responsible agency.
///
/// **Update freq**: 24 hours – whenever there are updates
#[derive(Debug, Clone, PartialEq)]
pub struct GetRoadWorksInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetRoadWorksInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetRoadWorksInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns road works currently in progress or planned, together with event details and the responsible agency.
///
/// **Update freq**: 24 hours – whenever there are updates
#[derive(Debug, Clone, PartialEq)]
pub enum GetRoadWorksResponse {
    /// Successful Road Works response.
    Ok(Vec<RoadDetails>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns road works currently in progress or planned, together with event details and the responsible agency.
///
/// **Update freq**: 24 hours – whenever there are updates
pub fn get_road_works_parts(
    input: GetRoadWorksInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(10);
    uri.push_str("/RoadWorks");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
