[package]
name = "lta"
version = "0.7.0"
authors = ["budinverse <me@inve.rs>"]
edition = "2024"
rust-version = "1.95"
homepage = "https://github.com/InfiniteUnion/lta-rs"
repository = "https://github.com/InfiniteUnion/lta-rs"
description = "🚍 Sans-IO Singapore LTA Datamall Rust Client"
readme = "README.md"
license = "MIT"
keywords = ["LTA", "Singapore", "Client", "Datamall"]
exclude = [
    "./.github"
]

[lib]
name = "lta"

[dependencies]
satay-runtime = { version = "0.17.2", default-features = false }
nutype = { version = "0.7", features = ["serde", "regex"] }
regex = "1"
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
http = "1"

[features]
default = ["serde", "json"]
serde = ["dep:serde", "satay-runtime/serde"]
json = ["serde", "dep:serde_json", "satay-runtime/json"]

[dev-dependencies]
argh = "0.1"
reqwest = "0.13.3"
satay-reqwest = { version = "0.17.2" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
assert_float_eq = "1"

[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/zeon256/style-rust-aku", branch = "main" }
]
