// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TaxiStand;
use super::parts::{GetTaxiStandsInput, GetTaxiStandsResponse, get_taxi_stands_parts};
use serde::de;
/// Returns detailed information of Taxi stands, such as location and whether it is barrier free.
///
/// **Update freq**: Monthly
pub fn encode_get_taxi_stands(
    input: GetTaxiStandsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_taxi_stands_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_taxi_stands_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetTaxiStandsResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value =
                satay_runtime::from_projected_json_slice::<Vec<TaxiStand<S>>>(body, "value", None)?;
            Ok(GetTaxiStandsResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetTaxiStandsResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
