// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TaxiStand;
/// Returns detailed information of Taxi stands, such as location and whether it is barrier free.
///
/// **Update freq**: Monthly
#[derive(Debug, Clone, PartialEq)]
pub struct GetTaxiStandsInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetTaxiStandsInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetTaxiStandsInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns detailed information of Taxi stands, such as location and whether it is barrier free.
///
/// **Update freq**: Monthly
#[derive(Debug, Clone, PartialEq)]
pub enum GetTaxiStandsResponse<S: satay_runtime::StringStorage = String> {
    /// Successful Taxi Stands response.
    Ok(Vec<TaxiStand<S>>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns detailed information of Taxi stands, such as location and whether it is barrier free.
///
/// **Update freq**: Monthly
pub fn get_taxi_stands_parts(
    input: GetTaxiStandsInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(11);
    uri.push_str("/TaxiStands");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
