// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::Vms;
use super::parts::{
    GetVariableMessageSignsInput, GetVariableMessageSignsResponse, get_variable_message_signs_parts,
};
use serde::de;
/// Returns traffic advisories (via variable message services) concerning current traffic conditions that are displayed on EMAS signboards along expressways and arterial roads.
///
/// **Update freq**: 2 minutes
pub fn encode_get_variable_message_signs(
    input: GetVariableMessageSignsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_variable_message_signs_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_variable_message_signs_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetVariableMessageSignsResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value =
                satay_runtime::from_projected_json_slice::<Vec<Vms<S>>>(body, "value", None)?;
            Ok(GetVariableMessageSignsResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetVariableMessageSignsResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
