// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::Vms;
/// Returns traffic advisories (via variable message services) concerning current traffic conditions that are displayed on EMAS signboards along expressways and arterial roads.
///
/// **Update freq**: 2 minutes
#[derive(Debug, Clone, PartialEq)]
pub struct GetVariableMessageSignsInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetVariableMessageSignsInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetVariableMessageSignsInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns traffic advisories (via variable message services) concerning current traffic conditions that are displayed on EMAS signboards along expressways and arterial roads.
///
/// **Update freq**: 2 minutes
#[derive(Debug, Clone, PartialEq)]
pub enum GetVariableMessageSignsResponse {
    /// Successful Variable Message Signs response.
    Ok(Vec<Vms>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns traffic advisories (via variable message services) concerning current traffic conditions that are displayed on EMAS signboards along expressways and arterial roads.
///
/// **Update freq**: 2 minutes
pub fn get_variable_message_signs_parts(
    input: GetVariableMessageSignsInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(4);
    uri.push_str("/VMS");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
