// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::FacilityMaintenanceV2;
use super::parts::{
    GetFacilitiesMaintenanceV2Input, GetFacilitiesMaintenanceV2Response,
    get_facilities_maintenance_v2_parts,
};
/// Returns ad hoc lift maintenance records for MRT stations.
///
/// **Update freq**: Ad-Hoc
pub fn encode_get_facilities_maintenance_v2(
    input: GetFacilitiesMaintenanceV2Input,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_facilities_maintenance_v2_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_facilities_maintenance_v2_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetFacilitiesMaintenanceV2Response, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<FacilityMaintenanceV2>>(
                body.as_ref(),
                "value",
                None,
            )?;
            Ok(GetFacilitiesMaintenanceV2Response::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetFacilitiesMaintenanceV2Response::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
