// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::FacilityMaintenanceV2;
/// Returns ad hoc lift maintenance records for MRT stations.
///
/// **Update freq**: Ad-Hoc
#[derive(Debug, Clone, PartialEq)]
pub struct GetFacilitiesMaintenanceV2Input {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetFacilitiesMaintenanceV2Input {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetFacilitiesMaintenanceV2Input {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns ad hoc lift maintenance records for MRT stations.
///
/// **Update freq**: Ad-Hoc
#[derive(Debug, Clone, PartialEq)]
pub enum GetFacilitiesMaintenanceV2Response {
    /// Successful Facilities Maintenance v2 response.
    Ok(Vec<FacilityMaintenanceV2>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns ad hoc lift maintenance records for MRT stations.
///
/// **Update freq**: Ad-Hoc
pub fn get_facilities_maintenance_v2_parts(
    input: GetFacilitiesMaintenanceV2Input,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(25);
    uri.push_str("/v2/FacilitiesMaintenance");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
