// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::RoadDetails;
use super::parts::{GetRoadOpeningsInput, GetRoadOpeningsResponse, get_road_openings_parts};
/// Returns all planned road openings, including the new road name and the responsible agency.
/// **Update freq**: 24 hours – whenever there are updates
pub fn encode_get_road_openings(
    input: GetRoadOpeningsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_road_openings_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_road_openings_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetRoadOpeningsResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<RoadDetails>>(
                body.as_ref(),
                "value",
                None,
            )?;
            Ok(GetRoadOpeningsResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetRoadOpeningsResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
