// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::parts::{
    GetEvChargingPointsBatchInput, GetEvChargingPointsBatchResponse,
    get_ev_charging_points_batch_parts,
};
/// Returns a link to a JSON file containing all EV charging-point availability in one downloadable file.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded JSON file, whose schema is undocumented and is not modeled here.
///
/// **Update freq**: 5 minutes
pub fn encode_get_ev_charging_points_batch(
    input: GetEvChargingPointsBatchInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_ev_charging_points_batch_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_ev_charging_points_batch_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetEvChargingPointsBatchResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<String>>(
                body.as_ref(),
                "value",
                Some("Link"),
            )?;
            Ok(GetEvChargingPointsBatchResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetEvChargingPointsBatchResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
