// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

/// Returns a link to a JSON file containing all EV charging-point availability in one downloadable file.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded JSON file, whose schema is undocumented and is not modeled here.
///
/// **Update freq**: 5 minutes
#[derive(Debug, Clone, PartialEq)]
pub struct GetEvChargingPointsBatchInput {}
impl GetEvChargingPointsBatchInput {
    pub fn new() -> Self {
        Self {}
    }
}
impl Default for GetEvChargingPointsBatchInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns a link to a JSON file containing all EV charging-point availability in one downloadable file.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded JSON file, whose schema is undocumented and is not modeled here.
///
/// **Update freq**: 5 minutes
#[derive(Debug, Clone, PartialEq)]
pub enum GetEvChargingPointsBatchResponse {
    /// Successful EV Charging Points Batch response.
    Ok(Vec<String>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns a link to a JSON file containing all EV charging-point availability in one downloadable file.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded JSON file, whose schema is undocumented and is not modeled here.
///
/// **Update freq**: 5 minutes
pub fn get_ev_charging_points_batch_parts(
    _input: GetEvChargingPointsBatchInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(9);
    uri.push_str("/EVCBatch");
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
