// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::BusArrivalResponse;
use super::parts::{GetBusArrivalInput, GetBusArrivalResponse, get_bus_arrival_parts};
/// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
/// - Estimated Arrival Time
/// - Estimated Current Location
/// - Estimated Current Load.
///
/// **Update freq**: 20s
pub fn encode_get_bus_arrival(
    input: GetBusArrivalInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_bus_arrival_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_bus_arrival_response(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetBusArrivalResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_json_slice::<BusArrivalResponse>(body)?;
            Ok(GetBusArrivalResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetBusArrivalResponse::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
