//! @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

#[cfg(feature = "json")]
mod json;
mod parts;
#[cfg(feature = "json")]
pub use json::*;
pub use parts::*;
