// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::{BusArrivalResponse, BusServiceNumber, BusStopCode};
/// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
/// - Estimated Arrival Time
/// - Estimated Current Location
/// - Estimated Current Load.
///
/// **Update freq**: 20s
#[derive(Debug, Clone, PartialEq)]
pub struct GetBusArrivalInput {
    /// Bus stop reference code.
    pub bus_stop_code: BusStopCode,
    /// Optional bus service number filter.
    pub service_no: Option<BusServiceNumber>,
}
impl GetBusArrivalInput {
    pub fn new(bus_stop_code: BusStopCode) -> Self {
        Self {
            bus_stop_code,
            service_no: None,
        }
    }
    pub fn service_no(mut self, service_no: BusServiceNumber) -> Self {
        self.service_no = Some(service_no);
        self
    }
}
/// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
/// - Estimated Arrival Time
/// - Estimated Current Location
/// - Estimated Current Load.
///
/// **Update freq**: 20s
#[derive(Debug, Clone, PartialEq)]
pub enum GetBusArrivalResponse {
    /// Successful Bus Arrival response.
    Ok(BusArrivalResponse),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
/// - Estimated Arrival Time
/// - Estimated Current Location
/// - Estimated Current Load.
///
/// **Update freq**: 20s
pub fn get_bus_arrival_parts(
    input: GetBusArrivalInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(14);
    uri.push_str("/v3/BusArrival");
    let mut first_query = true;
    satay_runtime::append_query_pair(
        &mut uri,
        &mut first_query,
        "BusStopCode",
        input.bus_stop_code.as_ref(),
    );
    if let Some(value) = &input.service_no {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "ServiceNo", value.as_ref());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
