// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::parts::{
    GetGtfsRealtimeTrainTripUpdatesInput, GetGtfsRealtimeTrainTripUpdatesResponse,
    get_gtfs_realtime_train_trip_updates_parts,
};
/// Returns a link to a protobuf file containing GTFS Realtime (Train Trip Updates - Disruption) predictions: real-time arrival and departure predictions, delays, cancellations and skipped stops during train service disruptions.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded protobuf file, whose decoding is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
pub fn encode_get_gtfs_realtime_train_trip_updates(
    input: GetGtfsRealtimeTrainTripUpdatesInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_gtfs_realtime_train_trip_updates_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_gtfs_realtime_train_trip_updates_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetGtfsRealtimeTrainTripUpdatesResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<String>>(
                body.as_ref(),
                "value",
                Some("link"),
            )?;
            Ok(GetGtfsRealtimeTrainTripUpdatesResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetGtfsRealtimeTrainTripUpdatesResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
