// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::BicycleParking;
use super::parts::{GetBikeParkingInput, GetBikeParkingResponse, get_bike_parking_parts};
use serde::de;
/// Returns bicycle parking locations within a radius of the queried coordinates.
/// Dist is default to 0.5 even if you provide `None`.
///
/// **Update freq**: Monthly
pub fn encode_get_bike_parking(
    input: GetBikeParkingInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_bike_parking_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_bike_parking_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetBikeParkingResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<BicycleParking<S>>>(
                body, "value", None,
            )?;
            Ok(GetBikeParkingResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetBikeParkingResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
