// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::{BicycleParking, Latitude, Longitude};
/// Returns bicycle parking locations within a radius of the queried coordinates.
/// Dist is default to 0.5 even if you provide `None`.
///
/// **Update freq**: Monthly
#[derive(Debug, Clone, PartialEq)]
pub struct GetBikeParkingInput {
    /// Latitude of the queried location.
    pub lat: Latitude,
    /// Longitude of the queried location.
    pub long: Longitude,
    /// Search radius in kilometers, defaulting to 0.5.
    pub dist: Option<f64>,
}
impl GetBikeParkingInput {
    pub fn new(lat: Latitude, long: Longitude) -> Self {
        Self {
            lat,
            long,
            dist: Some(0.5),
        }
    }
    pub fn dist(mut self, dist: f64) -> Self {
        self.dist = Some(dist);
        self
    }
}
/// Returns bicycle parking locations within a radius of the queried coordinates.
/// Dist is default to 0.5 even if you provide `None`.
///
/// **Update freq**: Monthly
#[derive(Debug, Clone, PartialEq)]
pub enum GetBikeParkingResponse<S: satay_runtime::StringStorage = String> {
    /// Successful Bicycle Parking response.
    Ok(Vec<BicycleParking<S>>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns bicycle parking locations within a radius of the queried coordinates.
/// Dist is default to 0.5 even if you provide `None`.
///
/// **Update freq**: Monthly
pub fn get_bike_parking_parts(
    input: GetBikeParkingInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(17);
    uri.push_str("/BicycleParkingv2");
    let mut first_query = true;
    satay_runtime::append_query_pair(&mut uri, &mut first_query, "Lat", &input.lat.to_string());
    satay_runtime::append_query_pair(&mut uri, &mut first_query, "Long", &input.long.to_string());
    if let Some(value) = &input.dist {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "Dist", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
