// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TrafficIncident;
use super::parts::{
    GetTrafficIncidentsInput, GetTrafficIncidentsResponse, get_traffic_incidents_parts,
};
use serde::de;
/// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
/// **Update freq**: 2 min
pub fn encode_get_traffic_incidents(
    input: GetTrafficIncidentsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_traffic_incidents_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_traffic_incidents_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetTrafficIncidentsResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<TrafficIncident<S>>>(
                body, "value", None,
            )?;
            Ok(GetTrafficIncidentsResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetTrafficIncidentsResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
