// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TrafficIncident;
use super::parts::{
    GetTrafficIncidentsInput, GetTrafficIncidentsResponse, get_traffic_incidents_parts,
};
/// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
/// **Update freq**: 2 min
pub fn encode_get_traffic_incidents(
    input: GetTrafficIncidentsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_traffic_incidents_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_traffic_incidents_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetTrafficIncidentsResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<TrafficIncident>>(
                body.as_ref(),
                "value",
                None,
            )?;
            Ok(GetTrafficIncidentsResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetTrafficIncidentsResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
