// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TrafficIncident;
/// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
/// **Update freq**: 2 min
#[derive(Debug, Clone, PartialEq)]
pub struct GetTrafficIncidentsInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetTrafficIncidentsInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetTrafficIncidentsInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
/// **Update freq**: 2 min
#[derive(Debug, Clone, PartialEq)]
pub enum GetTrafficIncidentsResponse<S: satay_runtime::StringStorage = String> {
    /// Successful Traffic Incidents response.
    Ok(Vec<TrafficIncident<S>>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
/// **Update freq**: 2 min
pub fn get_traffic_incidents_parts(
    input: GetTrafficIncidentsInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(17);
    uri.push_str("/TrafficIncidents");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
