// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::BusStop;
use super::parts::{GetBusStopsInput, GetBusStopsResponse, get_bus_stops_parts};
use serde::de;
/// Returns detailed information for all bus stops currently being serviced by buses, including bus stop codes and location coordinates.
///
/// **Update freq**: Ad-Hoc
pub fn encode_get_bus_stops(
    input: GetBusStopsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_bus_stops_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_bus_stops_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetBusStopsResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value =
                satay_runtime::from_projected_json_slice::<Vec<BusStop<S>>>(body, "value", None)?;
            Ok(GetBusStopsResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetBusStopsResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
