// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::BusStop;
use super::parts::{GetBusStopsInput, GetBusStopsResponse, get_bus_stops_parts};
/// Returns detailed information for all bus stops currently being serviced by buses, including bus stop codes and location coordinates.
///
/// **Update freq**: Ad-Hoc
pub fn encode_get_bus_stops(
    input: GetBusStopsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_bus_stops_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_bus_stops_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetBusStopsResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<BusStop>>(
                body.as_ref(),
                "value",
                None,
            )?;
            Ok(GetBusStopsResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetBusStopsResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
