// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::BusStop;
/// Returns detailed information for all bus stops currently being serviced by buses, including bus stop codes and location coordinates.
///
/// **Update freq**: Ad-Hoc
#[derive(Debug, Clone, PartialEq)]
pub struct GetBusStopsInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetBusStopsInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetBusStopsInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns detailed information for all bus stops currently being serviced by buses, including bus stop codes and location coordinates.
///
/// **Update freq**: Ad-Hoc
#[derive(Debug, Clone, PartialEq)]
pub enum GetBusStopsResponse {
    /// Successful Bus Stops response.
    Ok(Vec<BusStop>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns detailed information for all bus stops currently being serviced by buses, including bus stop codes and location coordinates.
///
/// **Update freq**: Ad-Hoc
pub fn get_bus_stops_parts(
    input: GetBusStopsInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(9);
    uri.push_str("/BusStops");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
