// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::CarPark;
use super::parts::{
    GetCarParkAvailabilityInput, GetCarParkAvailabilityResponse, get_car_park_availability_parts,
};
use serde::de;
/// Returns number of available lots for HDB, LTA and URA carpark data. The LTA carpark data consist of major shopping malls and developments within Orchard, Marina, HarbourFront, Jurong Lake District. (Note: list of LTA carpark data available on this API is subset of those listed on One.Motoring and MyTransport Portals)
///
/// **Update freq**: 1 min
pub fn encode_get_car_park_availability(
    input: GetCarParkAvailabilityInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_car_park_availability_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_car_park_availability_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetCarParkAvailabilityResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value =
                satay_runtime::from_projected_json_slice::<Vec<CarPark<S>>>(body, "value", None)?;
            Ok(GetCarParkAvailabilityResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetCarParkAvailabilityResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
