// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::CarPark;
/// Returns number of available lots for HDB, LTA and URA carpark data. The LTA carpark data consist of major shopping malls and developments within Orchard, Marina, HarbourFront, Jurong Lake District. (Note: list of LTA carpark data available on this API is subset of those listed on One.Motoring and MyTransport Portals)
///
/// **Update freq**: 1 min
#[derive(Debug, Clone, PartialEq)]
pub struct GetCarParkAvailabilityInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetCarParkAvailabilityInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetCarParkAvailabilityInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns number of available lots for HDB, LTA and URA carpark data. The LTA carpark data consist of major shopping malls and developments within Orchard, Marina, HarbourFront, Jurong Lake District. (Note: list of LTA carpark data available on this API is subset of those listed on One.Motoring and MyTransport Portals)
///
/// **Update freq**: 1 min
#[derive(Debug, Clone, PartialEq)]
pub enum GetCarParkAvailabilityResponse<S: satay_runtime::StringStorage = String> {
    /// Successful Car Park Availability response.
    Ok(Vec<CarPark<S>>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns number of available lots for HDB, LTA and URA carpark data. The LTA carpark data consist of major shopping malls and developments within Orchard, Marina, HarbourFront, Jurong Lake District. (Note: list of LTA carpark data available on this API is subset of those listed on One.Motoring and MyTransport Portals)
///
/// **Update freq**: 1 min
pub fn get_car_park_availability_parts(
    input: GetCarParkAvailabilityInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(22);
    uri.push_str("/CarParkAvailabilityv2");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
