// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TrafficImage;
use super::parts::{GetTrafficImagesInput, GetTrafficImagesResponse, get_traffic_images_parts};
/// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
/// **Update freq**: 20 sec
pub fn encode_get_traffic_images(
    input: GetTrafficImagesInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_traffic_images_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_traffic_images_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetTrafficImagesResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<TrafficImage>>(
                body.as_ref(),
                "value",
                None,
            )?;
            Ok(GetTrafficImagesResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetTrafficImagesResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
