// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TrafficImage;
/// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
/// **Update freq**: 20 sec
#[derive(Debug, Clone, PartialEq)]
pub struct GetTrafficImagesInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetTrafficImagesInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetTrafficImagesInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
/// **Update freq**: 20 sec
#[derive(Debug, Clone, PartialEq)]
pub enum GetTrafficImagesResponse {
    /// Successful Traffic Images response.
    Ok(Vec<TrafficImage>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
/// **Update freq**: 20 sec
pub fn get_traffic_images_parts(
    input: GetTrafficImagesInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(17);
    uri.push_str("/Traffic-Imagesv2");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
