// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::EvChargingPointsValue;
use super::parts::{
    GetEvChargingPointsInput, GetEvChargingPointsResponse, get_ev_charging_points_parts,
};
/// Returns electric vehicle charging points and their availabilities for a queried postal code.
///
/// Unlike other DataMall endpoints, the live wire response omits `odata.metadata` and nests locations as `{"value": {"evLocationsData": [...]}}`. An unknown postal code returns `{"value": {"evLocationsData": []}}`.
///
/// The DataMall guide documents the longitude field as `longtitude`; the live `/EVChargingPoints` wire uses the correct `longitude` spelling. The `/EVCBatch` downloadable file uses `longtitude`, `postalCode`, `current`/`powerRating(kW)` and omits `id` fields, while `/EVChargingPoints` uses `longitude`, `locationId`+`status`, `powerRating(AC/DC)`/`chargingSpeed(kW)` and includes `id` fields.
///
/// **Update freq**: 5 minutes
pub fn encode_get_ev_charging_points(
    input: GetEvChargingPointsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_ev_charging_points_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_ev_charging_points_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetEvChargingPointsResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<EvChargingPointsValue>(
                body.as_ref(),
                "value",
                None,
            )?;
            Ok(GetEvChargingPointsResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetEvChargingPointsResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
