// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::{EvChargingPointsValue, PostalCode};
/// Returns electric vehicle charging points and their availabilities for a queried postal code.
///
/// Unlike other DataMall endpoints, the live wire response omits `odata.metadata` and nests locations as `{"value": {"evLocationsData": [...]}}`. An unknown postal code returns `{"value": {"evLocationsData": []}}`.
///
/// The DataMall guide documents the longitude field as `longtitude`; the live `/EVChargingPoints` wire uses the correct `longitude` spelling. The `/EVCBatch` downloadable file uses `longtitude`, `postalCode`, `current`/`powerRating(kW)` and omits `id` fields, while `/EVChargingPoints` uses `longitude`, `locationId`+`status`, `powerRating(AC/DC)`/`chargingSpeed(kW)` and includes `id` fields.
///
/// **Update freq**: 5 minutes
#[derive(Debug, Clone, PartialEq)]
pub struct GetEvChargingPointsInput {
    /// 6-digit Singapore postal code of the location.
    pub postal_code: PostalCode,
    /// Number of records to skip for pagination. Accepted by the API but has no effect for postal-code queries.
    pub skip: Option<u32>,
}
impl GetEvChargingPointsInput {
    pub fn new(postal_code: PostalCode) -> Self {
        Self {
            postal_code,
            skip: None,
        }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
/// Returns electric vehicle charging points and their availabilities for a queried postal code.
///
/// Unlike other DataMall endpoints, the live wire response omits `odata.metadata` and nests locations as `{"value": {"evLocationsData": [...]}}`. An unknown postal code returns `{"value": {"evLocationsData": []}}`.
///
/// The DataMall guide documents the longitude field as `longtitude`; the live `/EVChargingPoints` wire uses the correct `longitude` spelling. The `/EVCBatch` downloadable file uses `longtitude`, `postalCode`, `current`/`powerRating(kW)` and omits `id` fields, while `/EVChargingPoints` uses `longitude`, `locationId`+`status`, `powerRating(AC/DC)`/`chargingSpeed(kW)` and includes `id` fields.
///
/// **Update freq**: 5 minutes
#[derive(Debug, Clone, PartialEq)]
pub enum GetEvChargingPointsResponse<S: satay_runtime::StringStorage = String> {
    /// Successful EV Charging Points response.
    Ok(EvChargingPointsValue<S>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns electric vehicle charging points and their availabilities for a queried postal code.
///
/// Unlike other DataMall endpoints, the live wire response omits `odata.metadata` and nests locations as `{"value": {"evLocationsData": [...]}}`. An unknown postal code returns `{"value": {"evLocationsData": []}}`.
///
/// The DataMall guide documents the longitude field as `longtitude`; the live `/EVChargingPoints` wire uses the correct `longitude` spelling. The `/EVCBatch` downloadable file uses `longtitude`, `postalCode`, `current`/`powerRating(kW)` and omits `id` fields, while `/EVChargingPoints` uses `longitude`, `locationId`+`status`, `powerRating(AC/DC)`/`chargingSpeed(kW)` and includes `id` fields.
///
/// **Update freq**: 5 minutes
pub fn get_ev_charging_points_parts(
    input: GetEvChargingPointsInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(17);
    uri.push_str("/EVChargingPoints");
    let mut first_query = true;
    satay_runtime::append_query_pair(
        &mut uri,
        &mut first_query,
        "PostalCode",
        input.postal_code.as_ref(),
    );
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
