// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::parts::{GetTrafficFlowInput, GetTrafficFlowResponse, get_traffic_flow_parts};
/// Returns a link to a JSON file containing hourly average traffic flow, taken from a representative month of every quarter during 0700-0900 hours.
/// **Update freq**: Quarterly
pub fn encode_get_traffic_flow(
    input: GetTrafficFlowInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_traffic_flow_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_traffic_flow_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetTrafficFlowResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<String>>(
                body.as_ref(),
                "value",
                Some("Link"),
            )?;
            Ok(GetTrafficFlowResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetTrafficFlowResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
