// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

/// Returns a link to a JSON file containing hourly average traffic flow, taken from a representative month of every quarter during 0700-0900 hours.
/// **Update freq**: Quarterly
#[derive(Debug, Clone, PartialEq)]
pub struct GetTrafficFlowInput {}
impl GetTrafficFlowInput {
    pub fn new() -> Self {
        Self {}
    }
}
impl Default for GetTrafficFlowInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns a link to a JSON file containing hourly average traffic flow, taken from a representative month of every quarter during 0700-0900 hours.
/// **Update freq**: Quarterly
#[derive(Debug, Clone, PartialEq)]
pub enum GetTrafficFlowResponse {
    /// Successful Traffic Flow response.
    Ok(Vec<satay_runtime::Url>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns a link to a JSON file containing hourly average traffic flow, taken from a representative month of every quarter during 0700-0900 hours.
/// **Update freq**: Quarterly
pub fn get_traffic_flow_parts(
    _input: GetTrafficFlowInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(12);
    uri.push_str("/TrafficFlow");
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
