// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::Coordinates;
use super::parts::{
    GetTaxiAvailabilityInput, GetTaxiAvailabilityResponse, get_taxi_availability_parts,
};
/// Returns the coordinates of all taxis currently available for hire.
///
/// **Update freq**: 1 min
pub fn encode_get_taxi_availability(
    input: GetTaxiAvailabilityInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_taxi_availability_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_taxi_availability_response(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetTaxiAvailabilityResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value =
                satay_runtime::from_projected_json_slice::<Vec<Coordinates>>(body, "value", None)?;
            Ok(GetTaxiAvailabilityResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetTaxiAvailabilityResponse::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
