// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::Coordinates;
/// Returns the coordinates of all taxis currently available for hire.
///
/// **Update freq**: 1 min
#[derive(Debug, Clone, PartialEq)]
pub struct GetTaxiAvailabilityInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetTaxiAvailabilityInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetTaxiAvailabilityInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns the coordinates of all taxis currently available for hire.
///
/// **Update freq**: 1 min
#[derive(Debug, Clone, PartialEq)]
pub enum GetTaxiAvailabilityResponse {
    /// Successful Taxi Availability response.
    Ok(Vec<Coordinates>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns the coordinates of all taxis currently available for hire.
///
/// **Update freq**: 1 min
pub fn get_taxi_availability_parts(
    input: GetTaxiAvailabilityInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(18);
    uri.push_str("/Taxi-Availability");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
