// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::parts::{
    GetGtfsScheduleTrainInput, GetGtfsScheduleTrainResponse, get_gtfs_schedule_train_parts,
};
/// Returns a link to a ZIP file containing the GTFS Schedule (Train) static feed: agency, routes, trips, stops, stop times, calendar and calendar dates text files in a single archive.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded ZIP file, whose parsing is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
pub fn encode_get_gtfs_schedule_train(
    input: GetGtfsScheduleTrainInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_gtfs_schedule_train_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_gtfs_schedule_train_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetGtfsScheduleTrainResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<String>>(
                body.as_ref(),
                "value",
                Some("link"),
            )?;
            Ok(GetGtfsScheduleTrainResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetGtfsScheduleTrainResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
