// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::FloodAlert;
use super::parts::{GetFloodAlertsInput, GetFloodAlertsResponse, get_flood_alerts_parts};
/// Returns flood alert information across Singapore, provided by PUB.
///
/// **Update freq**: 3 minutes
pub fn encode_get_flood_alerts(
    input: GetFloodAlertsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_flood_alerts_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_flood_alerts_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetFloodAlertsResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<FloodAlert>>(
                body.as_ref(),
                "value",
                None,
            )?;
            Ok(GetFloodAlertsResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetFloodAlertsResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
