// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::FloodAlert;
/// Returns flood alert information across Singapore, provided by PUB.
///
/// **Update freq**: 3 minutes
#[derive(Debug, Clone, PartialEq)]
pub struct GetFloodAlertsInput {}
impl GetFloodAlertsInput {
    pub fn new() -> Self {
        Self {}
    }
}
impl Default for GetFloodAlertsInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns flood alert information across Singapore, provided by PUB.
///
/// **Update freq**: 3 minutes
#[derive(Debug, Clone, PartialEq)]
pub enum GetFloodAlertsResponse<S: satay_runtime::StringStorage = String> {
    /// Successful Flood Alerts response.
    Ok(Vec<FloodAlert<S>>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns flood alert information across Singapore, provided by PUB.
///
/// **Update freq**: 3 minutes
pub fn get_flood_alerts_parts(
    _input: GetFloodAlertsInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(15);
    uri.push_str("/PubFloodAlerts");
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
