// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TrafficSpeedBand;
use super::parts::{
    GetTrafficSpeedBandsInput, GetTrafficSpeedBandsResponse, get_traffic_speed_bands_parts,
};
use serde::de;
/// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
///
/// **Update freq**: 5 min
pub fn encode_get_traffic_speed_bands(
    input: GetTrafficSpeedBandsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_traffic_speed_bands_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_traffic_speed_bands_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetTrafficSpeedBandsResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<TrafficSpeedBand<S>>>(
                body, "value", None,
            )?;
            Ok(GetTrafficSpeedBandsResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetTrafficSpeedBandsResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
