// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::TrafficSpeedBand;
/// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
///
/// **Update freq**: 5 min
#[derive(Debug, Clone, PartialEq)]
pub struct GetTrafficSpeedBandsInput {
    /// Number of records to skip for pagination.
    pub skip: Option<u32>,
}
impl GetTrafficSpeedBandsInput {
    pub fn new() -> Self {
        Self { skip: None }
    }
    pub fn skip(mut self, skip: u32) -> Self {
        self.skip = Some(skip);
        self
    }
}
impl Default for GetTrafficSpeedBandsInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
///
/// **Update freq**: 5 min
#[derive(Debug, Clone, PartialEq)]
pub enum GetTrafficSpeedBandsResponse {
    /// Successful Traffic Speed Bands response.
    Ok(Vec<TrafficSpeedBand>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
///
/// **Update freq**: 5 min
pub fn get_traffic_speed_bands_parts(
    input: GetTrafficSpeedBandsInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(21);
    uri.push_str("/v4/TrafficSpeedBands");
    let mut first_query = true;
    if let Some(value) = &input.skip {
        satay_runtime::append_query_pair(&mut uri, &mut first_query, "$skip", &value.to_string());
    }
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
