// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::parts::{
    GetFacilitiesMaintenanceInput, GetFacilitiesMaintenanceResponse,
    get_facilities_maintenance_parts,
};
/// Returns links to facility maintenance data files for a queried MRT/LRT station. Each link points to a JSON file describing the maintenance works currently in progress at that station.
///
/// **Update freq**: Ad-Hoc
pub fn encode_get_facilities_maintenance(
    input: GetFacilitiesMaintenanceInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_facilities_maintenance_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_facilities_maintenance_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetFacilitiesMaintenanceResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<String>>(
                body.as_ref(),
                "value",
                Some("Link"),
            )?;
            Ok(GetFacilitiesMaintenanceResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetFacilitiesMaintenanceResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
