// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::FacilityMaintenance;
use super::parts::{
    GetFacilitiesMaintenanceInput, GetFacilitiesMaintenanceResponse,
    get_facilities_maintenance_parts,
};
use serde::de;
/// Returns ad hoc lift maintenance records for MRT stations.
///
/// **Update freq**: Ad-Hoc
pub fn encode_get_facilities_maintenance(
    input: GetFacilitiesMaintenanceInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_facilities_maintenance_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_facilities_maintenance_response<
    S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned,
>(
    response: satay_runtime::ResponseParts<&[u8]>,
) -> Result<GetFacilitiesMaintenanceResponse<S>, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<FacilityMaintenance<S>>>(
                body, "value", None,
            )?;
            Ok(GetFacilitiesMaintenanceResponse::<S>::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetFacilitiesMaintenanceResponse::<S>::UnexpectedStatus(
                status,
                body.to_vec(),
            ))
        }
    }
}
