// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::super::types::StationCode;
/// Returns links to facility maintenance data files for a queried MRT/LRT station. Each link points to a JSON file describing the maintenance works currently in progress at that station.
///
/// **Update freq**: Ad-Hoc
#[derive(Debug, Clone, PartialEq)]
pub struct GetFacilitiesMaintenanceInput {
    /// MRT/LRT station code.
    pub station_code: StationCode,
}
impl GetFacilitiesMaintenanceInput {
    pub fn new(station_code: StationCode) -> Self {
        Self { station_code }
    }
}
/// Returns links to facility maintenance data files for a queried MRT/LRT station. Each link points to a JSON file describing the maintenance works currently in progress at that station.
///
/// **Update freq**: Ad-Hoc
#[derive(Debug, Clone, PartialEq)]
pub enum GetFacilitiesMaintenanceResponse {
    /// Successful Facilities Maintenance response.
    Ok(Vec<String>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns links to facility maintenance data files for a queried MRT/LRT station. Each link points to a JSON file describing the maintenance works currently in progress at that station.
///
/// **Update freq**: Ad-Hoc
pub fn get_facilities_maintenance_parts(
    input: GetFacilitiesMaintenanceInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(22);
    uri.push_str("/FacilitiesMaintenance");
    let mut first_query = true;
    satay_runtime::append_query_pair(
        &mut uri,
        &mut first_query,
        "StationCode",
        input.station_code.as_ref(),
    );
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
