//! @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::{
    BusServiceNumber, GetBusArrivalAcceptParameter, GetBusArrivalInput, GetBusArrivalResponse,
    decode_get_bus_arrival_response, get_bus_arrival_parts,
};
#[derive(Debug, Clone)]
pub struct Api {
    base_url: String,
    account_key: Option<String>,
}
impl Default for Api {
    fn default() -> Self {
        Self::new()
    }
}
impl Api {
    pub fn new() -> Self {
        Self {
            base_url: super::SERVER_URL.to_owned(),
            account_key: None,
        }
    }
    pub fn base_url(mut self, base_url: impl Into<String>) -> Self {
        self.base_url = base_url.into();
        self
    }
    pub fn account_key(mut self, value: impl Into<String>) -> Self {
        self.account_key = Some(value.into());
        self
    }
    /// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
    /// - Estimated Arrival Time
    /// - Estimated Current Location
    /// - Estimated Current Load.
    ///
    /// **Update freq**: 20s
    pub fn get_bus_arrival(&self, bus_stop_code: u32) -> GetBusArrivalAction<'_> {
        GetBusArrivalAction {
            api: self,
            input: GetBusArrivalInput::new(bus_stop_code),
        }
    }
    fn apply<B>(
        &self,
        parts: &mut satay_runtime::RequestParts<B>,
    ) -> Result<(), satay_runtime::Error> {
        if let Some(value) = &self.account_key {
            satay_runtime::insert_header(&mut parts.headers, "AccountKey", value)?;
        }
        if self.base_url.is_empty() {
            return Ok(());
        }
        let path_and_query = parts.uri.as_str();
        let base_url = self.base_url.trim_end_matches('/');
        let separator = if path_and_query.starts_with('/') {
            ""
        } else {
            "/"
        };
        parts.uri = format!("{base_url}{separator}{path_and_query}");
        Ok(())
    }
}
/// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
/// - Estimated Arrival Time
/// - Estimated Current Location
/// - Estimated Current Load.
///
/// **Update freq**: 20s
#[derive(Debug, Clone)]
pub struct GetBusArrivalAction<'a> {
    api: &'a Api,
    input: GetBusArrivalInput,
}
impl GetBusArrivalAction<'_> {
    pub fn service_no(mut self, service_no: BusServiceNumber) -> Self {
        self.input = self.input.service_no(service_no);
        self
    }
    pub fn accept(mut self, accept: GetBusArrivalAcceptParameter) -> Self {
        self.input = self.input.accept(accept);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_bus_arrival_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode<B: AsRef<[u8]>>(
        response: satay_runtime::ResponseParts<B>,
    ) -> Result<GetBusArrivalResponse, satay_runtime::Error> {
        decode_get_bus_arrival_response(response)
    }
}
impl satay_runtime::Action for GetBusArrivalAction<'_> {
    type Response = GetBusArrivalResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode<B: AsRef<[u8]>>(
        response: satay_runtime::ResponseParts<B>,
    ) -> Result<Self::Response, satay_runtime::Error> {
        Self::decode(response)
    }
}
