// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::get_bike_parking::{decode_get_bike_parking_response, get_bike_parking_parts};
use super::get_bus_arrival::{decode_get_bus_arrival_response, get_bus_arrival_parts};
use super::get_bus_stops::{decode_get_bus_stops_response, get_bus_stops_parts};
use super::get_car_park_availability::{
    decode_get_car_park_availability_response, get_car_park_availability_parts,
};
use super::get_ev_charging_points::{
    decode_get_ev_charging_points_response, get_ev_charging_points_parts,
};
use super::get_ev_charging_points_batch::{
    decode_get_ev_charging_points_batch_response, get_ev_charging_points_batch_parts,
};
use super::get_facilities_maintenance::{
    decode_get_facilities_maintenance_response, get_facilities_maintenance_parts,
};
use super::get_flood_alerts::{decode_get_flood_alerts_response, get_flood_alerts_parts};
use super::get_gtfs_real_time_train_service_alerts::{
    decode_get_gtfs_real_time_train_service_alerts_response,
    get_gtfs_real_time_train_service_alerts_parts,
};
use super::get_gtfs_realtime_train_trip_updates::{
    decode_get_gtfs_realtime_train_trip_updates_response,
    get_gtfs_realtime_train_trip_updates_parts,
};
use super::get_gtfs_schedule_train::{
    decode_get_gtfs_schedule_train_response, get_gtfs_schedule_train_parts,
};
use super::get_road_openings::{decode_get_road_openings_response, get_road_openings_parts};
use super::get_road_works::{decode_get_road_works_response, get_road_works_parts};
use super::get_taxi_availability::{
    decode_get_taxi_availability_response, get_taxi_availability_parts,
};
use super::get_taxi_stands::{decode_get_taxi_stands_response, get_taxi_stands_parts};
use super::get_traffic_flow::{decode_get_traffic_flow_response, get_traffic_flow_parts};
use super::get_traffic_images::{decode_get_traffic_images_response, get_traffic_images_parts};
use super::get_traffic_incidents::{
    decode_get_traffic_incidents_response, get_traffic_incidents_parts,
};
use super::get_traffic_speed_bands::{
    decode_get_traffic_speed_bands_response, get_traffic_speed_bands_parts,
};
use super::get_variable_message_signs::{
    decode_get_variable_message_signs_response, get_variable_message_signs_parts,
};
use super::{
    BusServiceNumber, BusStopCode, GetBikeParkingInput, GetBikeParkingResponse, GetBusArrivalInput,
    GetBusArrivalResponse, GetBusStopsInput, GetBusStopsResponse, GetCarParkAvailabilityInput,
    GetCarParkAvailabilityResponse, GetEvChargingPointsBatchInput,
    GetEvChargingPointsBatchResponse, GetEvChargingPointsInput, GetEvChargingPointsResponse,
    GetFacilitiesMaintenanceInput, GetFacilitiesMaintenanceResponse, GetFloodAlertsInput,
    GetFloodAlertsResponse, GetGtfsRealTimeTrainServiceAlertsInput,
    GetGtfsRealTimeTrainServiceAlertsResponse, GetGtfsRealtimeTrainTripUpdatesInput,
    GetGtfsRealtimeTrainTripUpdatesResponse, GetGtfsScheduleTrainInput,
    GetGtfsScheduleTrainResponse, GetRoadOpeningsInput, GetRoadOpeningsResponse, GetRoadWorksInput,
    GetRoadWorksResponse, GetTaxiAvailabilityInput, GetTaxiAvailabilityResponse,
    GetTaxiStandsInput, GetTaxiStandsResponse, GetTrafficFlowInput, GetTrafficFlowResponse,
    GetTrafficImagesInput, GetTrafficImagesResponse, GetTrafficIncidentsInput,
    GetTrafficIncidentsResponse, GetTrafficSpeedBandsInput, GetTrafficSpeedBandsResponse,
    GetVariableMessageSignsInput, GetVariableMessageSignsResponse, Latitude, Longitude, PostalCode,
};
use crate::bus;
use crate::ev;
use crate::facility;
use crate::taxi;
use crate::traffic;
use crate::train;
use serde::de;
use std::marker;
#[derive(Debug, Clone)]
pub struct Api<S: satay_runtime::StringStorage = String> {
    base_url: String,
    account_key: Option<String>,
    __satay_storage: marker::PhantomData<fn() -> S>,
}
impl<S: satay_runtime::StringStorage> Default for Api<S> {
    fn default() -> Self {
        Api::new().string_storage()
    }
}
impl<S: satay_runtime::StringStorage> Api<S> {
    pub fn base_url(mut self, base_url: impl Into<String>) -> Self {
        self.base_url = base_url.into();
        self
    }
    pub fn account_key(mut self, value: impl Into<String>) -> Self {
        self.account_key = Some(value.into());
        self
    }
    /// Access operations tagged `bus`.
    pub fn bus(&self) -> bus::Api<'_, S> {
        bus::Api { api: self }
    }
    /// Access operations tagged `traffic`.
    pub fn traffic(&self) -> traffic::Api<'_, S> {
        traffic::Api { api: self }
    }
    /// Access operations tagged `taxi`.
    pub fn taxi(&self) -> taxi::Api<'_, S> {
        taxi::Api { api: self }
    }
    /// Access operations tagged `facility`.
    pub fn facility(&self) -> facility::Api<'_, S> {
        facility::Api { api: self }
    }
    /// Access operations tagged `ev`.
    pub fn ev(&self) -> ev::Api<'_, S> {
        ev::Api { api: self }
    }
    /// Access operations tagged `train`.
    pub fn train(&self) -> train::Api<'_, S> {
        train::Api { api: self }
    }
    fn apply<B>(
        &self,
        parts: &mut satay_runtime::RequestParts<B>,
    ) -> Result<(), satay_runtime::Error> {
        if let Some(value) = &self.account_key {
            satay_runtime::insert_header(&mut parts.headers, "AccountKey", value)?;
        }
        if self.base_url.is_empty() {
            return Ok(());
        }
        let path_and_query = parts.uri.as_str();
        let base_url = self.base_url.trim_end_matches('/');
        let separator = if path_and_query.starts_with('/') {
            ""
        } else {
            "/"
        };
        parts.uri = format!("{base_url}{separator}{path_and_query}");
        Ok(())
    }
    /// Selects dynamic string storage for generated models and actions.
    pub fn string_storage<T: satay_runtime::StringStorage>(self) -> Api<T> {
        Api {
            base_url: self.base_url,
            account_key: self.account_key,
            __satay_storage: marker::PhantomData,
        }
    }
}
/// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
/// - Estimated Arrival Time
/// - Estimated Current Location
/// - Estimated Current Load.
///
/// **Update freq**: 20s
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetBusArrivalAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetBusArrivalInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetBusArrivalAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>, bus_stop_code: BusStopCode) -> Self {
        Self {
            api,
            input: GetBusArrivalInput::new(bus_stop_code),
        }
    }
    /// Optional bus service number filter.
    #[must_use = "builder methods return the configured action"]
    pub fn service_no(mut self, service_no: BusServiceNumber) -> Self {
        self.input = self.input.service_no(service_no);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_bus_arrival_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetBusArrivalResponse, satay_runtime::Error> {
        decode_get_bus_arrival_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetBusArrivalAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetBusArrivalResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetBusArrivalAction<'_, S>
{
    type OwnedResponse = GetBusArrivalResponse;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
/// **Update freq**: 2 min
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetTrafficIncidentsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetTrafficIncidentsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetTrafficIncidentsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetTrafficIncidentsInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_traffic_incidents_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetTrafficIncidentsResponse<S>, satay_runtime::Error> {
        decode_get_traffic_incidents_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetTrafficIncidentsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetTrafficIncidentsResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetTrafficIncidentsAction<'_, S>
{
    type OwnedResponse = GetTrafficIncidentsResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns traffic advisories (via variable message services) concerning current traffic conditions that are displayed on EMAS signboards along expressways and arterial roads.
///
/// **Update freq**: 2 minutes
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetVariableMessageSignsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetVariableMessageSignsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetVariableMessageSignsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetVariableMessageSignsInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_variable_message_signs_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetVariableMessageSignsResponse<S>, satay_runtime::Error> {
        decode_get_variable_message_signs_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetVariableMessageSignsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetVariableMessageSignsResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetVariableMessageSignsAction<'_, S>
{
    type OwnedResponse = GetVariableMessageSignsResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
/// **Update freq**: 20 sec
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetTrafficImagesAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetTrafficImagesInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetTrafficImagesAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetTrafficImagesInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_traffic_images_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetTrafficImagesResponse, satay_runtime::Error> {
        decode_get_traffic_images_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetTrafficImagesAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetTrafficImagesResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetTrafficImagesAction<'_, S>
{
    type OwnedResponse = GetTrafficImagesResponse;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
///
/// **Update freq**: 5 min
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetTrafficSpeedBandsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetTrafficSpeedBandsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetTrafficSpeedBandsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetTrafficSpeedBandsInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_traffic_speed_bands_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetTrafficSpeedBandsResponse<S>, satay_runtime::Error> {
        decode_get_traffic_speed_bands_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetTrafficSpeedBandsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetTrafficSpeedBandsResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetTrafficSpeedBandsAction<'_, S>
{
    type OwnedResponse = GetTrafficSpeedBandsResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns a link to a JSON file containing hourly average traffic flow, taken from a representative month of every quarter during 0700-0900 hours.
/// **Update freq**: Quarterly
///
/// Call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetTrafficFlowAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetTrafficFlowInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetTrafficFlowAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetTrafficFlowInput::new(),
        }
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_traffic_flow_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetTrafficFlowResponse, satay_runtime::Error> {
        decode_get_traffic_flow_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetTrafficFlowAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetTrafficFlowResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetTrafficFlowAction<'_, S>
{
    type OwnedResponse = GetTrafficFlowResponse;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns bicycle parking locations within a radius of the queried coordinates.
/// Dist is default to 0.5 even if you provide `None`.
///
/// **Update freq**: Monthly
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetBikeParkingAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetBikeParkingInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetBikeParkingAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>, lat: Latitude, long: Longitude) -> Self {
        Self {
            api,
            input: GetBikeParkingInput::new(lat, long),
        }
    }
    /// Search radius in kilometers, defaulting to 0.5.
    #[must_use = "builder methods return the configured action"]
    pub fn dist(mut self, dist: f64) -> Self {
        self.input = self.input.dist(dist);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_bike_parking_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetBikeParkingResponse<S>, satay_runtime::Error> {
        decode_get_bike_parking_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetBikeParkingAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetBikeParkingResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetBikeParkingAction<'_, S>
{
    type OwnedResponse = GetBikeParkingResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns number of available lots for HDB, LTA and URA carpark data. The LTA carpark data consist of major shopping malls and developments within Orchard, Marina, HarbourFront, Jurong Lake District. (Note: list of LTA carpark data available on this API is subset of those listed on One.Motoring and MyTransport Portals)
///
/// **Update freq**: 1 min
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetCarParkAvailabilityAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetCarParkAvailabilityInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetCarParkAvailabilityAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetCarParkAvailabilityInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_car_park_availability_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetCarParkAvailabilityResponse<S>, satay_runtime::Error> {
        decode_get_car_park_availability_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetCarParkAvailabilityAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetCarParkAvailabilityResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetCarParkAvailabilityAction<'_, S>
{
    type OwnedResponse = GetCarParkAvailabilityResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns road works currently in progress or planned, together with event details and the responsible agency.
///
/// **Update freq**: 24 hours – whenever there are updates
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetRoadWorksAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetRoadWorksInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetRoadWorksAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetRoadWorksInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_road_works_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetRoadWorksResponse<S>, satay_runtime::Error> {
        decode_get_road_works_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetRoadWorksAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetRoadWorksResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetRoadWorksAction<'_, S>
{
    type OwnedResponse = GetRoadWorksResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns all planned road openings, including the new road name and the responsible agency.
/// **Update freq**: 24 hours – whenever there are updates
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetRoadOpeningsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetRoadOpeningsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetRoadOpeningsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetRoadOpeningsInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_road_openings_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetRoadOpeningsResponse<S>, satay_runtime::Error> {
        decode_get_road_openings_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetRoadOpeningsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetRoadOpeningsResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetRoadOpeningsAction<'_, S>
{
    type OwnedResponse = GetRoadOpeningsResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns flood alert information across Singapore, provided by PUB.
///
/// **Update freq**: 3 minutes
///
/// Call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetFloodAlertsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetFloodAlertsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetFloodAlertsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetFloodAlertsInput::new(),
        }
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_flood_alerts_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetFloodAlertsResponse<S>, satay_runtime::Error> {
        decode_get_flood_alerts_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetFloodAlertsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetFloodAlertsResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetFloodAlertsAction<'_, S>
{
    type OwnedResponse = GetFloodAlertsResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns a link to a JSON file containing all EV charging-point availability in one downloadable file.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded JSON file, whose schema is undocumented and is not modeled here.
///
/// **Update freq**: 5 minutes
///
/// Call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetEvChargingPointsBatchAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetEvChargingPointsBatchInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetEvChargingPointsBatchAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetEvChargingPointsBatchInput::new(),
        }
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_ev_charging_points_batch_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetEvChargingPointsBatchResponse, satay_runtime::Error> {
        decode_get_ev_charging_points_batch_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetEvChargingPointsBatchAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetEvChargingPointsBatchResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetEvChargingPointsBatchAction<'_, S>
{
    type OwnedResponse = GetEvChargingPointsBatchResponse;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns electric vehicle charging points and their availabilities for a queried postal code.
///
/// Unlike other DataMall endpoints, the live wire response omits `odata.metadata` and nests locations as `{"value": {"evLocationsData": [...]}}`. An unknown postal code returns `{"value": {"evLocationsData": []}}`.
///
/// The DataMall guide documents the longitude field as `longtitude`; the live `/EVChargingPoints` wire uses the correct `longitude` spelling. The `/EVCBatch` downloadable file uses `longtitude`, `postalCode`, `current`/`powerRating(kW)` and omits `id` fields, while `/EVChargingPoints` uses `longitude`, `locationId`+`status`, `powerRating(AC/DC)`/`chargingSpeed(kW)` and includes `id` fields.
///
/// **Update freq**: 5 minutes
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetEvChargingPointsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetEvChargingPointsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetEvChargingPointsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>, postal_code: PostalCode) -> Self {
        Self {
            api,
            input: GetEvChargingPointsInput::new(postal_code),
        }
    }
    /// Number of records to skip for pagination. Accepted by the API but has no effect for postal-code queries.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_ev_charging_points_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetEvChargingPointsResponse<S>, satay_runtime::Error> {
        decode_get_ev_charging_points_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetEvChargingPointsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetEvChargingPointsResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetEvChargingPointsAction<'_, S>
{
    type OwnedResponse = GetEvChargingPointsResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns detailed information for all bus stops currently being serviced by buses, including bus stop codes and location coordinates.
///
/// **Update freq**: Ad-Hoc
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetBusStopsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetBusStopsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetBusStopsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetBusStopsInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    /// Fixed-width 5-digit bus stop reference code. Supplying it filters the response to the specified physical stop; omitting it returns all stops.
    #[must_use = "builder methods return the configured action"]
    pub fn bus_stop_code(mut self, bus_stop_code: BusStopCode) -> Self {
        self.input = self.input.bus_stop_code(bus_stop_code);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_bus_stops_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetBusStopsResponse<S>, satay_runtime::Error> {
        decode_get_bus_stops_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetBusStopsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetBusStopsResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetBusStopsAction<'_, S>
{
    type OwnedResponse = GetBusStopsResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns the coordinates of all taxis currently available for hire.
///
/// **Update freq**: 1 min
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetTaxiAvailabilityAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetTaxiAvailabilityInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetTaxiAvailabilityAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetTaxiAvailabilityInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_taxi_availability_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetTaxiAvailabilityResponse, satay_runtime::Error> {
        decode_get_taxi_availability_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetTaxiAvailabilityAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetTaxiAvailabilityResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetTaxiAvailabilityAction<'_, S>
{
    type OwnedResponse = GetTaxiAvailabilityResponse;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns detailed information of Taxi stands, such as location and whether it is barrier free.
///
/// **Update freq**: Monthly
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetTaxiStandsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetTaxiStandsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetTaxiStandsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetTaxiStandsInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_taxi_stands_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetTaxiStandsResponse<S>, satay_runtime::Error> {
        decode_get_taxi_stands_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetTaxiStandsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetTaxiStandsResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetTaxiStandsAction<'_, S>
{
    type OwnedResponse = GetTaxiStandsResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns ad hoc lift maintenance records for MRT stations.
///
/// **Update freq**: Ad-Hoc
///
/// Use the chainable methods to configure optional request settings, then call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetFacilitiesMaintenanceAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetFacilitiesMaintenanceInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetFacilitiesMaintenanceAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetFacilitiesMaintenanceInput::new(),
        }
    }
    /// Number of records to skip for pagination.
    #[must_use = "builder methods return the configured action"]
    pub fn skip(mut self, skip: u32) -> Self {
        self.input = self.input.skip(skip);
        self
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_facilities_maintenance_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetFacilitiesMaintenanceResponse<S>, satay_runtime::Error> {
        decode_get_facilities_maintenance_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetFacilitiesMaintenanceAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetFacilitiesMaintenanceResponse<S>;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetFacilitiesMaintenanceAction<'_, S>
{
    type OwnedResponse = GetFacilitiesMaintenanceResponse<S>;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns a link to a ZIP file containing the GTFS Schedule (Train) static feed: agency, routes, trips, stops, stop times, calendar and calendar dates text files in a single archive.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded ZIP file, whose parsing is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
///
/// Call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetGtfsScheduleTrainAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetGtfsScheduleTrainInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetGtfsScheduleTrainAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetGtfsScheduleTrainInput::new(),
        }
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_gtfs_schedule_train_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetGtfsScheduleTrainResponse, satay_runtime::Error> {
        decode_get_gtfs_schedule_train_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetGtfsScheduleTrainAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetGtfsScheduleTrainResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetGtfsScheduleTrainAction<'_, S>
{
    type OwnedResponse = GetGtfsScheduleTrainResponse;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns a link to a protobuf file containing GTFS Realtime (Train Service Alerts) service alerts: unforeseen events affecting a station, route or the entire network.
/// This is distinct from the legacy JSON TrainServiceAlerts records.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded protobuf file, whose decoding is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
///
/// Call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetGtfsRealTimeTrainServiceAlertsAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetGtfsRealTimeTrainServiceAlertsInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetGtfsRealTimeTrainServiceAlertsAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetGtfsRealTimeTrainServiceAlertsInput::new(),
        }
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_gtfs_real_time_train_service_alerts_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetGtfsRealTimeTrainServiceAlertsResponse, satay_runtime::Error> {
        decode_get_gtfs_real_time_train_service_alerts_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetGtfsRealTimeTrainServiceAlertsAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetGtfsRealTimeTrainServiceAlertsResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetGtfsRealTimeTrainServiceAlertsAction<'_, S>
{
    type OwnedResponse = GetGtfsRealTimeTrainServiceAlertsResponse;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
/// Returns a link to a protobuf file containing GTFS Realtime (Train Trip Updates - Disruption) predictions: real-time arrival and departure predictions, delays, cancellations and skipped stops during train service disruptions.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded protobuf file, whose decoding is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
///
/// Call [`Self::request`] or use a transport adapter.
#[must_use = "configure this action and execute it or call `.request()`"]
#[derive(Debug, Clone)]
pub struct GetGtfsRealtimeTrainTripUpdatesAction<'a, S: satay_runtime::StringStorage = String> {
    api: &'a Api<S>,
    input: GetGtfsRealtimeTrainTripUpdatesInput,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    GetGtfsRealtimeTrainTripUpdatesAction<'a, S>
{
    pub(crate) fn new(api: &'a Api<S>) -> Self {
        Self {
            api,
            input: GetGtfsRealtimeTrainTripUpdatesInput::new(),
        }
    }
    pub fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        let api = self.api;
        let mut parts = get_gtfs_realtime_train_trip_updates_parts(self.input)?;
        api.apply(&mut parts)?;
        satay_runtime::into_empty_request(parts)
    }
    pub fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<GetGtfsRealtimeTrainTripUpdatesResponse, satay_runtime::Error> {
        decode_get_gtfs_realtime_train_trip_updates_response(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::Action for GetGtfsRealtimeTrainTripUpdatesAction<'_, S>
{
    type RequestBody = Vec<u8>;
    type Response<'de> = GetGtfsRealtimeTrainTripUpdatesResponse;
    fn request(self) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
        self.request()
    }
    fn decode(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::Response<'_>, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl<S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned>
    satay_runtime::OwnedAction for GetGtfsRealtimeTrainTripUpdatesAction<'_, S>
{
    type OwnedResponse = GetGtfsRealtimeTrainTripUpdatesResponse;
    fn decode_owned(
        response: satay_runtime::ResponseParts<&[u8]>,
    ) -> Result<Self::OwnedResponse, satay_runtime::Error> {
        Self::decode(response)
    }
}
impl Api<String> {
    pub fn new() -> Self {
        Self {
            base_url: super::SERVER_URL.to_owned(),
            account_key: None,
            __satay_storage: marker::PhantomData,
        }
    }
}
