// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::{Api as RootApi, GetBusArrivalAction};
/// Bus related operations.
#[derive(Debug, Clone, Copy)]
pub struct Api<'a> {
    pub(crate) api: &'a RootApi,
}
impl<'a> Api<'a> {
    /// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
    /// - Estimated Arrival Time
    /// - Estimated Current Location
    /// - Estimated Current Load.
    ///
    /// **Update freq**: 20s
    ///
    /// # Arguments
    ///
    /// - `bus_stop_code`: Bus stop reference code.
    ///
    /// # Optional request settings
    ///
    /// - [`service_no`](GetBusArrivalAction::service_no): Optional bus service number filter.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .bus()
    ///     .get_arrival(bus_stop_code)
    ///     .service_no(service_no)
    ///     .request()?;
    /// ```
    pub fn get_arrival(&self, bus_stop_code: u32) -> GetBusArrivalAction<'a> {
        GetBusArrivalAction::new(self.api, bus_stop_code)
    }
}
