// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::{Api as RootApi, GetEvChargingPointsBatchAction};
/// Electric Vehicle (EV) related operations.
#[derive(Debug, Clone, Copy)]
pub struct Api<'a> {
    pub(crate) api: &'a RootApi,
}
impl<'a> Api<'a> {
    /// Returns a link to a JSON file containing all EV charging-point availability in one downloadable file.
    /// Each pre-signed link expires after 15 minutes.
    /// The API response is the link wrapper, not the downloaded JSON file, whose schema is undocumented and is not modeled here.
    ///
    /// **Update freq**: 5 minutes
    pub fn get_charging_points_batch(&self) -> GetEvChargingPointsBatchAction<'a> {
        GetEvChargingPointsBatchAction::new(self.api)
    }
}
