// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::{Api as RootApi, GetFacilitiesMaintenanceAction};
use serde::de;
/// Facility related operations.
#[derive(Debug, Clone, Copy)]
pub struct Api<'a, S: satay_runtime::StringStorage = String> {
    pub(crate) api: &'a RootApi<S>,
}
impl<'a, S: satay_runtime::StringStorage + serde::Serialize + de::DeserializeOwned> Api<'a, S> {
    /// Returns ad hoc lift maintenance records for MRT stations.
    ///
    /// **Update freq**: Ad-Hoc
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetFacilitiesMaintenanceAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .facility()
    ///     .get_facilities_maintenance()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_facilities_maintenance(&self) -> GetFacilitiesMaintenanceAction<'a, S> {
        GetFacilitiesMaintenanceAction::<S>::new(self.api)
    }
}
