// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::{Api as RootApi, GetFacilitiesMaintenanceAction, StationCode};
/// Facility related operations.
#[derive(Debug, Clone, Copy)]
pub struct Api<'a> {
    pub(crate) api: &'a RootApi,
}
impl<'a> Api<'a> {
    /// Returns links to facility maintenance data files for a queried MRT/LRT station. Each link points to a JSON file describing the maintenance works currently in progress at that station.
    ///
    /// **Update freq**: Ad-Hoc
    ///
    /// # Arguments
    ///
    /// - `station_code`: MRT/LRT station code.
    pub fn get_facilities_maintenance(
        &self,
        station_code: StationCode,
    ) -> GetFacilitiesMaintenanceAction<'a> {
        GetFacilitiesMaintenanceAction::new(self.api, station_code)
    }
}
