// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

/// Default Upstream URL
pub const SERVER_URL: &str = "https://datamall2.mytransport.sg/ltaodataservice";
/// Where all types, structs and enums are
pub mod types;
pub use types::*;
#[cfg(feature = "json")]
mod api;
#[cfg(feature = "json")]
pub use api::*;
/// Bus related operations.
#[cfg(feature = "json")]
pub mod bus;
/// Electric Vehicle (EV) related operations.
#[cfg(feature = "json")]
pub mod ev;
/// Facility related operations.
#[cfg(feature = "json")]
pub mod facility;
mod get_bus_arrival;
/// Taxi related operations.
#[cfg(feature = "json")]
pub mod taxi;
/// Traffic related operations.
#[cfg(feature = "json")]
pub mod traffic;
pub use get_bus_arrival::{GetBusArrivalInput, GetBusArrivalResponse};
mod get_traffic_incidents;
pub use get_traffic_incidents::{GetTrafficIncidentsInput, GetTrafficIncidentsResponse};
mod get_variable_message_signs;
pub use get_variable_message_signs::{
    GetVariableMessageSignsInput, GetVariableMessageSignsResponse,
};
mod get_traffic_images;
pub use get_traffic_images::{GetTrafficImagesInput, GetTrafficImagesResponse};
mod get_traffic_speed_bands;
pub use get_traffic_speed_bands::{GetTrafficSpeedBandsInput, GetTrafficSpeedBandsResponse};
mod get_traffic_flow;
pub use get_traffic_flow::{GetTrafficFlowInput, GetTrafficFlowResponse};
mod get_bike_parking;
pub use get_bike_parking::{GetBikeParkingInput, GetBikeParkingResponse};
mod get_road_works;
pub use get_road_works::{GetRoadWorksInput, GetRoadWorksResponse};
mod get_road_openings;
pub use get_road_openings::{GetRoadOpeningsInput, GetRoadOpeningsResponse};
mod get_flood_alerts;
pub use get_flood_alerts::{GetFloodAlertsInput, GetFloodAlertsResponse};
mod get_ev_charging_points_batch;
pub use get_ev_charging_points_batch::{
    GetEvChargingPointsBatchInput, GetEvChargingPointsBatchResponse,
};
mod get_ev_charging_points;
pub use get_ev_charging_points::{GetEvChargingPointsInput, GetEvChargingPointsResponse};
mod get_bus_stops;
pub use get_bus_stops::{GetBusStopsInput, GetBusStopsResponse};
mod get_taxi_availability;
pub use get_taxi_availability::{GetTaxiAvailabilityInput, GetTaxiAvailabilityResponse};
mod get_taxi_stands;
pub use get_taxi_stands::{GetTaxiStandsInput, GetTaxiStandsResponse};
mod get_facilities_maintenance;
pub use get_facilities_maintenance::{
    GetFacilitiesMaintenanceInput, GetFacilitiesMaintenanceResponse,
};
/// Low-level request parts and response codecs, organized by operation.
pub mod operations {
    /// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
    /// - Estimated Arrival Time
    /// - Estimated Current Location
    /// - Estimated Current Load.
    ///
    /// **Update freq**: 20s
    pub mod get_bus_arrival {
        #[cfg(feature = "json")]
        pub use super::super::GetBusArrivalAction;
        pub use super::super::get_bus_arrival::*;
    }
    /// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
    /// **Update freq**: 2 min
    pub mod get_traffic_incidents {
        #[cfg(feature = "json")]
        pub use super::super::GetTrafficIncidentsAction;
        pub use super::super::get_traffic_incidents::*;
    }
    /// Returns traffic advisories (via variable message services) concerning current traffic conditions that are displayed on EMAS signboards along expressways and arterial roads.
    ///
    /// **Update freq**: 2 minutes
    pub mod get_variable_message_signs {
        #[cfg(feature = "json")]
        pub use super::super::GetVariableMessageSignsAction;
        pub use super::super::get_variable_message_signs::*;
    }
    /// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
    /// **Update freq**: 20 sec
    pub mod get_traffic_images {
        #[cfg(feature = "json")]
        pub use super::super::GetTrafficImagesAction;
        pub use super::super::get_traffic_images::*;
    }
    /// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
    ///
    /// **Update freq**: 5 min
    pub mod get_traffic_speed_bands {
        #[cfg(feature = "json")]
        pub use super::super::GetTrafficSpeedBandsAction;
        pub use super::super::get_traffic_speed_bands::*;
    }
    /// Returns a link to a JSON file containing hourly average traffic flow, taken from a representative month of every quarter during 0700-0900 hours.
    /// **Update freq**: Quarterly
    pub mod get_traffic_flow {
        #[cfg(feature = "json")]
        pub use super::super::GetTrafficFlowAction;
        pub use super::super::get_traffic_flow::*;
    }
    /// Returns bicycle parking locations within a radius of the queried coordinates.
    /// Dist is default to 0.5 even if you provide `None`.
    ///
    /// **Update freq**: Monthly
    pub mod get_bike_parking {
        #[cfg(feature = "json")]
        pub use super::super::GetBikeParkingAction;
        pub use super::super::get_bike_parking::*;
    }
    /// Returns road works currently in progress or planned, together with event details and the responsible agency.
    ///
    /// **Update freq**: 24 hours – whenever there are updates
    pub mod get_road_works {
        #[cfg(feature = "json")]
        pub use super::super::GetRoadWorksAction;
        pub use super::super::get_road_works::*;
    }
    /// Returns all planned road openings, including the new road name and the responsible agency.
    /// **Update freq**: 24 hours – whenever there are updates
    pub mod get_road_openings {
        #[cfg(feature = "json")]
        pub use super::super::GetRoadOpeningsAction;
        pub use super::super::get_road_openings::*;
    }
    /// Returns flood alert information across Singapore, provided by PUB.
    ///
    /// **Update freq**: 3 minutes
    pub mod get_flood_alerts {
        #[cfg(feature = "json")]
        pub use super::super::GetFloodAlertsAction;
        pub use super::super::get_flood_alerts::*;
    }
    /// Returns a link to a JSON file containing all EV charging-point availability in one downloadable file.
    /// Each pre-signed link expires after 15 minutes.
    /// The API response is the link wrapper, not the downloaded JSON file, whose schema is undocumented and is not modeled here.
    ///
    /// **Update freq**: 5 minutes
    pub mod get_ev_charging_points_batch {
        #[cfg(feature = "json")]
        pub use super::super::GetEvChargingPointsBatchAction;
        pub use super::super::get_ev_charging_points_batch::*;
    }
    /// Returns electric vehicle charging points and their availabilities for a queried postal code.
    ///
    /// Unlike other DataMall endpoints, the live wire response omits `odata.metadata` and nests locations as `{"value": {"evLocationsData": [...]}}`. An unknown postal code returns `{"value": {"evLocationsData": []}}`.
    ///
    /// The DataMall guide documents the longitude field as `longtitude`; the live `/EVChargingPoints` wire uses the correct `longitude` spelling. The `/EVCBatch` downloadable file uses `longtitude`, `postalCode`, `current`/`powerRating(kW)` and omits `id` fields, while `/EVChargingPoints` uses `longitude`, `locationId`+`status`, `powerRating(AC/DC)`/`chargingSpeed(kW)` and includes `id` fields.
    ///
    /// **Update freq**: 5 minutes
    pub mod get_ev_charging_points {
        #[cfg(feature = "json")]
        pub use super::super::GetEvChargingPointsAction;
        pub use super::super::get_ev_charging_points::*;
    }
    /// Returns detailed information for all bus stops currently being serviced by buses, including bus stop codes and location coordinates.
    ///
    /// **Update freq**: Ad-Hoc
    pub mod get_bus_stops {
        #[cfg(feature = "json")]
        pub use super::super::GetBusStopsAction;
        pub use super::super::get_bus_stops::*;
    }
    /// Returns the coordinates of all taxis currently available for hire.
    ///
    /// **Update freq**: 1 min
    pub mod get_taxi_availability {
        #[cfg(feature = "json")]
        pub use super::super::GetTaxiAvailabilityAction;
        pub use super::super::get_taxi_availability::*;
    }
    /// Returns detailed information of Taxi stands, such as location and whether it is barrier free.
    ///
    /// **Update freq**: Monthly
    pub mod get_taxi_stands {
        #[cfg(feature = "json")]
        pub use super::super::GetTaxiStandsAction;
        pub use super::super::get_taxi_stands::*;
    }
    /// Returns ad hoc lift maintenance records for MRT stations.
    ///
    /// **Update freq**: Ad-Hoc
    pub mod get_facilities_maintenance {
        #[cfg(feature = "json")]
        pub use super::super::GetFacilitiesMaintenanceAction;
        pub use super::super::get_facilities_maintenance::*;
    }
}
