// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

/// Default Upstream URL
pub const SERVER_URL: &str = "https://datamall2.mytransport.sg/ltaodataservice";
/// Where all types, structs and enums are
pub mod types;
pub use types::*;
#[cfg(feature = "json")]
mod api;
#[cfg(feature = "json")]
pub use api::*;
/// Bus related operations.
#[cfg(feature = "json")]
pub mod bus;
/// Facility related operations.
#[cfg(feature = "json")]
pub mod facility;
mod get_bus_arrival;
/// Taxi related operations.
#[cfg(feature = "json")]
pub mod taxi;
/// Traffic related operations.
#[cfg(feature = "json")]
pub mod traffic;
pub use get_bus_arrival::{GetBusArrivalInput, GetBusArrivalResponse};
mod get_traffic_incidents;
pub use get_traffic_incidents::{GetTrafficIncidentsInput, GetTrafficIncidentsResponse};
mod get_traffic_images;
pub use get_traffic_images::{GetTrafficImagesInput, GetTrafficImagesResponse};
mod get_traffic_speed_bands;
pub use get_traffic_speed_bands::{GetTrafficSpeedBandsInput, GetTrafficSpeedBandsResponse};
mod get_traffic_flow;
pub use get_traffic_flow::{GetTrafficFlowInput, GetTrafficFlowResponse};
mod get_road_works;
pub use get_road_works::{GetRoadWorksInput, GetRoadWorksResponse};
mod get_road_openings;
pub use get_road_openings::{GetRoadOpeningsInput, GetRoadOpeningsResponse};
mod get_bus_stops;
pub use get_bus_stops::{GetBusStopsInput, GetBusStopsResponse};
mod get_taxi_availability;
pub use get_taxi_availability::{GetTaxiAvailabilityInput, GetTaxiAvailabilityResponse};
mod get_taxi_stands;
pub use get_taxi_stands::{GetTaxiStandsInput, GetTaxiStandsResponse};
mod get_facilities_maintenance;
pub use get_facilities_maintenance::{
    GetFacilitiesMaintenanceInput, GetFacilitiesMaintenanceResponse,
};
/// Low-level request parts and response codecs, organized by operation.
pub mod operations {
    /// Returns real-time Bus Arrival information of Bus Services at a queried Bus Stop, including
    /// - Estimated Arrival Time
    /// - Estimated Current Location
    /// - Estimated Current Load.
    ///
    /// **Update freq**: 20s
    pub mod get_bus_arrival {
        #[cfg(feature = "json")]
        pub use super::super::GetBusArrivalAction;
        pub use super::super::get_bus_arrival::*;
    }
    /// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
    /// **Update freq**: 2 min
    pub mod get_traffic_incidents {
        #[cfg(feature = "json")]
        pub use super::super::GetTrafficIncidentsAction;
        pub use super::super::get_traffic_incidents::*;
    }
    /// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
    /// **Update freq**: 20 sec
    pub mod get_traffic_images {
        #[cfg(feature = "json")]
        pub use super::super::GetTrafficImagesAction;
        pub use super::super::get_traffic_images::*;
    }
    /// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
    ///
    /// **Update freq**: 5 min
    pub mod get_traffic_speed_bands {
        #[cfg(feature = "json")]
        pub use super::super::GetTrafficSpeedBandsAction;
        pub use super::super::get_traffic_speed_bands::*;
    }
    /// Returns a link to a JSON file containing hourly average traffic flow, taken from a representative month of every quarter during 0700-0900 hours.
    /// **Update freq**: Quarterly
    pub mod get_traffic_flow {
        #[cfg(feature = "json")]
        pub use super::super::GetTrafficFlowAction;
        pub use super::super::get_traffic_flow::*;
    }
    /// Returns road works currently in progress or planned, together with event details and the responsible agency.
    ///
    /// **Update freq**: 24 hours – whenever there are updates
    pub mod get_road_works {
        #[cfg(feature = "json")]
        pub use super::super::GetRoadWorksAction;
        pub use super::super::get_road_works::*;
    }
    /// Returns all planned road openings, including the new road name and the responsible agency.
    /// **Update freq**: 24 hours – whenever there are updates
    pub mod get_road_openings {
        #[cfg(feature = "json")]
        pub use super::super::GetRoadOpeningsAction;
        pub use super::super::get_road_openings::*;
    }
    /// Returns detailed information for all bus stops currently being serviced by buses, including bus stop codes and location coordinates.
    ///
    /// **Update freq**: Ad-Hoc
    pub mod get_bus_stops {
        #[cfg(feature = "json")]
        pub use super::super::GetBusStopsAction;
        pub use super::super::get_bus_stops::*;
    }
    /// Returns the coordinates of all taxis currently available for hire.
    ///
    /// **Update freq**: 1 min
    pub mod get_taxi_availability {
        #[cfg(feature = "json")]
        pub use super::super::GetTaxiAvailabilityAction;
        pub use super::super::get_taxi_availability::*;
    }
    /// Returns detailed information of Taxi stands, such as location and whether it is barrier free.
    ///
    /// **Update freq**: Monthly
    pub mod get_taxi_stands {
        #[cfg(feature = "json")]
        pub use super::super::GetTaxiStandsAction;
        pub use super::super::get_taxi_stands::*;
    }
    /// Returns links to facility maintenance data files for a queried MRT/LRT station. Each link points to a JSON file describing the maintenance works currently in progress at that station.
    ///
    /// **Update freq**: Ad-Hoc
    pub mod get_facilities_maintenance {
        #[cfg(feature = "json")]
        pub use super::super::GetFacilitiesMaintenanceAction;
        pub use super::super::get_facilities_maintenance::*;
    }
}
