// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::{Api as RootApi, GetTaxiAvailabilityAction};
/// Taxi related operations.
#[derive(Debug, Clone, Copy)]
pub struct Api<'a> {
    pub(crate) api: &'a RootApi,
}
impl<'a> Api<'a> {
    /// Returns the coordinates of all taxis currently available for hire.
    ///
    /// **Update freq**: 1 min
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetTaxiAvailabilityAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .taxi()
    ///     .get_availability()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_availability(&self) -> GetTaxiAvailabilityAction<'a> {
        GetTaxiAvailabilityAction::new(self.api)
    }
}
