// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::{
    Api as RootApi, GetTrafficImagesAction, GetTrafficIncidentsAction, GetTrafficSpeedBandsAction,
};
/// Traffic related operations.
#[derive(Debug, Clone, Copy)]
pub struct Api<'a> {
    pub(crate) api: &'a RootApi,
}
impl<'a> Api<'a> {
    /// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
    /// **Update freq**: 2 min
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetTrafficIncidentsAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_incidents()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_incidents(&self) -> GetTrafficIncidentsAction<'a> {
        GetTrafficIncidentsAction::new(self.api)
    }
    /// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
    /// **Update freq**: 20 sec
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetTrafficImagesAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_images()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_images(&self) -> GetTrafficImagesAction<'a> {
        GetTrafficImagesAction::new(self.api)
    }
    /// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
    ///
    /// **Update freq**: 5 min
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetTrafficSpeedBandsAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_speed_bands()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_speed_bands(&self) -> GetTrafficSpeedBandsAction<'a> {
        GetTrafficSpeedBandsAction::new(self.api)
    }
}
