// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::{
    Api as RootApi, GetBikeParkingAction, GetRoadOpeningsAction, GetRoadWorksAction,
    GetTrafficFlowAction, GetTrafficImagesAction, GetTrafficIncidentsAction,
    GetTrafficSpeedBandsAction, GetVariableMessageSignsAction, Latitude, Longitude,
};
/// Traffic related operations.
#[derive(Debug, Clone, Copy)]
pub struct Api<'a> {
    pub(crate) api: &'a RootApi,
}
impl<'a> Api<'a> {
    /// Returns incidents currently happening on the roads, such as Accidents, Vehicle Breakdowns, Road Blocks, Traffic Diversions etc.
    /// **Update freq**: 2 min
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetTrafficIncidentsAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_incidents()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_incidents(&self) -> GetTrafficIncidentsAction<'a> {
        GetTrafficIncidentsAction::new(self.api)
    }
    /// Returns traffic advisories (via variable message services) concerning current traffic conditions that are displayed on EMAS signboards along expressways and arterial roads.
    ///
    /// **Update freq**: 2 minutes
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetVariableMessageSignsAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_variable_message_signs()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_variable_message_signs(&self) -> GetVariableMessageSignsAction<'a> {
        GetVariableMessageSignsAction::new(self.api)
    }
    /// Returns links to images from traffic cameras located around Singapore, together with each camera's location coordinates.
    /// **Update freq**: 20 sec
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetTrafficImagesAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_images()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_images(&self) -> GetTrafficImagesAction<'a> {
        GetTrafficImagesAction::new(self.api)
    }
    /// Returns current traffic speeds on expressways and arterial roads, expressed in speed bands.
    ///
    /// **Update freq**: 5 min
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetTrafficSpeedBandsAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_speed_bands()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_speed_bands(&self) -> GetTrafficSpeedBandsAction<'a> {
        GetTrafficSpeedBandsAction::new(self.api)
    }
    /// Returns a link to a JSON file containing hourly average traffic flow, taken from a representative month of every quarter during 0700-0900 hours.
    /// **Update freq**: Quarterly
    pub fn get_flow(&self) -> GetTrafficFlowAction<'a> {
        GetTrafficFlowAction::new(self.api)
    }
    /// Returns bicycle parking locations within a radius of the queried coordinates.
    /// Dist is default to 0.5 even if you provide `None`.
    ///
    /// **Update freq**: Monthly
    ///
    /// # Arguments
    ///
    /// - `lat`: Latitude of the queried location.
    /// - `long`: Longitude of the queried location.
    ///
    /// # Optional request settings
    ///
    /// - [`dist`](GetBikeParkingAction::dist): Search radius in kilometers, defaulting to 0.5.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_bike_parking(lat, long)
    ///     .dist(dist)
    ///     .request()?;
    /// ```
    pub fn get_bike_parking(&self, lat: Latitude, long: Longitude) -> GetBikeParkingAction<'a> {
        GetBikeParkingAction::new(self.api, lat, long)
    }
    /// Returns road works currently in progress or planned, together with event details and the responsible agency.
    ///
    /// **Update freq**: 24 hours – whenever there are updates
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetRoadWorksAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_road_works()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_road_works(&self) -> GetRoadWorksAction<'a> {
        GetRoadWorksAction::new(self.api)
    }
    /// Returns all planned road openings, including the new road name and the responsible agency.
    /// **Update freq**: 24 hours – whenever there are updates
    ///
    /// # Optional request settings
    ///
    /// - [`skip`](GetRoadOpeningsAction::skip): Number of records to skip for pagination.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let request = api
    ///     .traffic()
    ///     .get_road_openings()
    ///     .skip(skip)
    ///     .request()?;
    /// ```
    pub fn get_road_openings(&self) -> GetRoadOpeningsAction<'a> {
        GetRoadOpeningsAction::new(self.api)
    }
}
