// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use std::fmt;
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BusArrivalResponse {
    /// Unique 5-digit bus stop reference code.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "BusStopCode", with = "satay_runtime::serde_string::as_u32")
    )]
    pub bus_stop_code: u32,
    /// Bus services serving the queried bus stop.
    #[cfg_attr(feature = "serde", serde(rename = "Services"))]
    pub services: Vec<BusServiceArrival>,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BusServiceArrival {
    /// Bus service number.
    #[cfg_attr(feature = "serde", serde(rename = "ServiceNo"))]
    pub service_no: BusServiceNumber,
    /// Public transport operator code.
    #[cfg_attr(feature = "serde", serde(rename = "Operator"))]
    pub operator: BusOperator,
    #[cfg_attr(
        feature = "serde",
        serde(
            rename = "NextBus",
            deserialize_with = "satay_runtime::treat_error_as_none::deserialize",
            serialize_with = "satay_runtime::treat_error_as_none::serialize",
            default,
            skip_serializing_if = "Option::is_none"
        )
    )]
    pub next_bus: Option<BusArrivalTiming>,
    #[cfg_attr(
        feature = "serde",
        serde(
            rename = "NextBus2",
            deserialize_with = "satay_runtime::treat_error_as_none::deserialize",
            serialize_with = "satay_runtime::treat_error_as_none::serialize",
            default,
            skip_serializing_if = "Option::is_none"
        )
    )]
    pub next_bus2: Option<BusArrivalTiming>,
    #[cfg_attr(
        feature = "serde",
        serde(
            rename = "NextBus3",
            deserialize_with = "satay_runtime::treat_error_as_none::deserialize",
            serialize_with = "satay_runtime::treat_error_as_none::serialize",
            default,
            skip_serializing_if = "Option::is_none"
        )
    )]
    pub next_bus3: Option<BusArrivalTiming>,
}
/// Public transport operator code.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum BusOperator {
    #[cfg_attr(feature = "serde", serde(rename = "SBST"))]
    Sbst,
    #[cfg_attr(feature = "serde", serde(rename = "SMRT"))]
    Smrt,
    #[cfg_attr(feature = "serde", serde(rename = "TTS"))]
    Tts,
    #[cfg_attr(feature = "serde", serde(rename = "GAS"))]
    Gas,
}
impl BusOperator {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::Sbst => "SBST",
            Self::Smrt => "SMRT",
            Self::Tts => "TTS",
            Self::Gas => "GAS",
        }
    }
}
impl AsRef<str> for BusOperator {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl fmt::Display for BusOperator {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
/// Bus service number.
#[nutype::nutype(
    validate(regex = "^[a-zA-Z0-9]+$", len_char_max = 5),
    derive(
        Debug, Clone, PartialEq, Eq, PartialOrd, Ord, AsRef, Deref, TryFrom, Into, Display, Hash
    ),
    cfg_attr(feature = "serde", derive(Serialize, Deserialize))
)]
pub struct BusServiceNumber(String);
/// Unique 5-digit bus stop reference code.
pub type BusStopCode = u32;
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BusArrivalTiming {
    /// Unique 5-digit bus stop reference code.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "OriginCode", with = "satay_runtime::serde_string::as_u32")
    )]
    pub origin_code: u32,
    /// Unique 5-digit bus stop reference code.
    #[cfg_attr(
        feature = "serde",
        serde(
            rename = "DestinationCode",
            with = "satay_runtime::serde_string::as_u32"
        )
    )]
    pub destination_code: u32,
    /// Estimated arrival date-time in Singapore Standard Time.
    #[cfg_attr(
        feature = "serde",
        serde(
            rename = "EstimatedArrival",
            with = "satay_runtime::serde_string::as_offset_datetime"
        )
    )]
    pub estimated_arrival: satay_runtime::OffsetDateTime,
    /// Current estimated latitude of the bus.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "Latitude", with = "satay_runtime::serde_string::as_f64")
    )]
    pub latitude: f64,
    /// Current estimated longitude of the bus.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "Longitude", with = "satay_runtime::serde_string::as_f64")
    )]
    pub longitude: f64,
    /// Ordinal visit number of this vehicle at the bus stop.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "VisitNumber", with = "satay_runtime::serde_string::as_u8")
    )]
    pub visit_number: u8,
    /// Current occupancy level.
    #[cfg_attr(feature = "serde", serde(rename = "Load"))]
    pub load: BusArrivalTimingLoad,
    /// Wheelchair accessibility indicator.
    #[cfg_attr(feature = "serde", serde(rename = "Feature"))]
    pub feature: BusArrivalTimingFeature,
    /// Vehicle type of the bus.
    #[cfg_attr(feature = "serde", serde(rename = "Type"))]
    pub r#type: BusArrivalTimingType,
    /// Whether the bus is currently monitored by the system.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "Monitored", with = "satay_runtime::serde_integer::as_bool")
    )]
    pub monitored: bool,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BusStopsResponse {
    /// Bus stops in this response page.
    pub value: Vec<BusStop>,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BusStop {
    /// Unique 5-digit bus stop reference code.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "BusStopCode", with = "satay_runtime::serde_string::as_u32")
    )]
    pub bus_stop_code: u32,
    /// Road on which the bus stop is located.
    #[cfg_attr(feature = "serde", serde(rename = "RoadName"))]
    pub road_name: String,
    /// Bus stop landmark or location description.
    #[cfg_attr(feature = "serde", serde(rename = "Description"))]
    pub desc: String,
    /// Latitude of the bus stop.
    #[cfg_attr(feature = "serde", serde(rename = "Latitude"))]
    pub lat: f64,
    /// Longitude of the bus stop.
    #[cfg_attr(feature = "serde", serde(rename = "Longitude"))]
    pub long: f64,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TrafficImagesResponse {
    /// Traffic camera images in this response page.
    pub value: Vec<TrafficImage>,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TrafficImage {
    /// Numeric identifier of the traffic camera.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "CameraID", with = "satay_runtime::serde_string::as_u32")
    )]
    pub camera_id: u32,
    /// Latitude of the traffic camera.
    #[cfg_attr(feature = "serde", serde(rename = "Latitude"))]
    pub lat: f64,
    /// Longitude of the traffic camera.
    #[cfg_attr(feature = "serde", serde(rename = "Longitude"))]
    pub long: f64,
    /// URL of the latest image from the traffic camera.
    #[cfg_attr(feature = "serde", serde(rename = "ImageLink"))]
    pub image_link: String,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TrafficSpeedBandsResponse {
    /// Traffic speed bands in this response page.
    pub value: Vec<TrafficSpeedBand>,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TrafficSpeedBand {
    /// Numeric identifier of the road link.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "LinkID", with = "satay_runtime::serde_string::as_u64")
    )]
    pub link_id: u64,
    /// Name of the road.
    #[cfg_attr(feature = "serde", serde(rename = "RoadName"))]
    pub road_name: String,
    /// Classification of the road carrying the traffic-speed reading.
    #[cfg_attr(feature = "serde", serde(rename = "RoadCategory"))]
    pub road_category: RoadCategory,
    /// Speed-band number assigned to the road link.
    #[cfg_attr(feature = "serde", serde(rename = "SpeedBand"))]
    pub speed_band: u32,
    /// Lower speed bound in kilometres per hour.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "MinimumSpeed", with = "satay_runtime::serde_string::as_u32")
    )]
    pub min_speed: u32,
    /// Upper speed bound in kilometres per hour.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "MaximumSpeed", with = "satay_runtime::serde_string::as_u32")
    )]
    pub max_speed: u32,
    /// Longitude of the road link's start point.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "StartLon", with = "satay_runtime::serde_string::as_f64")
    )]
    pub start_lon: f64,
    /// Latitude of the road link's start point.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "StartLat", with = "satay_runtime::serde_string::as_f64")
    )]
    pub start_lat: f64,
    /// Longitude of the road link's end point.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "EndLon", with = "satay_runtime::serde_string::as_f64")
    )]
    pub end_lon: f64,
    /// Latitude of the road link's end point.
    #[cfg_attr(
        feature = "serde",
        serde(rename = "EndLat", with = "satay_runtime::serde_string::as_f64")
    )]
    pub end_lat: f64,
}
/// Classification of the road carrying the traffic-speed reading.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RoadCategory {
    Expressway,
    MajorArterialRoads,
    ArterialRoads,
    MinorArterialRoads,
    SmallRoads,
    SlipRoads,
    NoCategoryInfoAvail,
    Other(String),
}
impl RoadCategory {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Expressway => "A",
            Self::MajorArterialRoads => "B",
            Self::ArterialRoads => "C",
            Self::MinorArterialRoads => "D",
            Self::SmallRoads => "E",
            Self::SlipRoads => "F",
            Self::NoCategoryInfoAvail => "G",
            Self::Other(value) => value.as_str(),
        }
    }
}
impl AsRef<str> for RoadCategory {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl fmt::Display for RoadCategory {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
#[cfg(feature = "serde")]
impl serde::Serialize for RoadCategory {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}
#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for RoadCategory {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "A" => Self::Expressway,
            "B" => Self::MajorArterialRoads,
            "C" => Self::ArterialRoads,
            "D" => Self::MinorArterialRoads,
            "E" => Self::SmallRoads,
            "F" => Self::SlipRoads,
            "G" => Self::NoCategoryInfoAvail,
            _ => Self::Other(value),
        })
    }
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TrafficIncidentsResponse {
    /// Traffic incidents in this response page.
    pub value: Vec<TrafficIncident>,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TrafficIncident {
    /// Type of traffic incident.
    #[cfg_attr(feature = "serde", serde(rename = "Type"))]
    pub incident_type: IncidentType,
    /// Latitude of the traffic incident.
    #[cfg_attr(feature = "serde", serde(rename = "Latitude"))]
    pub lat: f64,
    /// Longitude of the traffic incident.
    #[cfg_attr(feature = "serde", serde(rename = "Longitude"))]
    pub long: f64,
    /// Human-readable description of the traffic incident.
    #[cfg_attr(feature = "serde", serde(rename = "Message"))]
    pub msg: String,
}
/// Type of traffic incident.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IncidentType {
    Accident,
    RoadWorks,
    VehicleBreakdown,
    Weather,
    Obstacle,
    RoadBlock,
    HeavyTraffic,
    Misc,
    Diversion,
    UnattendedVehicle,
    Roadwork,
    Other(String),
}
impl IncidentType {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Accident => "Accident",
            Self::RoadWorks => "Road Works",
            Self::VehicleBreakdown => "Vehicle breakdown",
            Self::Weather => "Weather",
            Self::Obstacle => "Obstacle",
            Self::RoadBlock => "Road Block",
            Self::HeavyTraffic => "Heavy Traffic",
            Self::Misc => "Misc.",
            Self::Diversion => "Diversion",
            Self::UnattendedVehicle => "Unattended Vehicle",
            Self::Roadwork => "Roadwork",
            Self::Other(value) => value.as_str(),
        }
    }
}
impl AsRef<str> for IncidentType {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl fmt::Display for IncidentType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
#[cfg(feature = "serde")]
impl serde::Serialize for IncidentType {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}
#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for IncidentType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Ok(match value.as_str() {
            "Accident" => Self::Accident,
            "Road Works" => Self::RoadWorks,
            "Vehicle breakdown" => Self::VehicleBreakdown,
            "Weather" => Self::Weather,
            "Obstacle" => Self::Obstacle,
            "Road Block" => Self::RoadBlock,
            "Heavy Traffic" => Self::HeavyTraffic,
            "Misc." => Self::Misc,
            "Diversion" => Self::Diversion,
            "Unattended Vehicle" => Self::UnattendedVehicle,
            "Roadwork" => Self::Roadwork,
            _ => Self::Other(value),
        })
    }
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TaxiAvailabilityResponse {
    /// Coordinates of available taxis in this response page.
    pub value: Vec<Coordinates>,
}
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Coordinates {
    /// Latitude of the taxi.
    #[cfg_attr(feature = "serde", serde(rename = "Latitude"))]
    pub lat: f64,
    /// Longitude of the taxi.
    #[cfg_attr(feature = "serde", serde(rename = "Longitude"))]
    pub long: f64,
}
/// Current occupancy level.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum BusArrivalTimingLoad {
    #[cfg_attr(feature = "serde", serde(rename = "SEA"))]
    SeatsAvailable,
    #[cfg_attr(feature = "serde", serde(rename = "SDA"))]
    StandingAvailable,
    #[cfg_attr(feature = "serde", serde(rename = "LSD"))]
    LimitedStanding,
    #[cfg_attr(feature = "serde", serde(rename = ""))]
    Unspecified,
}
impl BusArrivalTimingLoad {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::SeatsAvailable => "SEA",
            Self::StandingAvailable => "SDA",
            Self::LimitedStanding => "LSD",
            Self::Unspecified => "",
        }
    }
}
impl AsRef<str> for BusArrivalTimingLoad {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl fmt::Display for BusArrivalTimingLoad {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
/// Wheelchair accessibility indicator.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum BusArrivalTimingFeature {
    #[cfg_attr(feature = "serde", serde(rename = "WAB"))]
    WheelchairAccessible,
    #[cfg_attr(feature = "serde", serde(rename = ""))]
    Unspecified,
}
impl BusArrivalTimingFeature {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::WheelchairAccessible => "WAB",
            Self::Unspecified => "",
        }
    }
}
impl AsRef<str> for BusArrivalTimingFeature {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl fmt::Display for BusArrivalTimingFeature {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
/// Vehicle type of the bus.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum BusArrivalTimingType {
    #[cfg_attr(feature = "serde", serde(rename = "SD"))]
    SingleDecker,
    #[cfg_attr(feature = "serde", serde(rename = "DD"))]
    DoubleDecker,
    #[cfg_attr(feature = "serde", serde(rename = "BD"))]
    Bendy,
    #[cfg_attr(feature = "serde", serde(rename = ""))]
    Unspecified,
}
impl BusArrivalTimingType {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::SingleDecker => "SD",
            Self::DoubleDecker => "DD",
            Self::Bendy => "BD",
            Self::Unspecified => "",
        }
    }
}
impl AsRef<str> for BusArrivalTimingType {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl fmt::Display for BusArrivalTimingType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
