// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

use super::parts::{
    GetGtfsRealTimeTrainServiceAlertsInput, GetGtfsRealTimeTrainServiceAlertsResponse,
    get_gtfs_real_time_train_service_alerts_parts,
};
/// Returns a link to a protobuf file containing GTFS Realtime (Train Service Alerts) service alerts: unforeseen events affecting a station, route or the entire network.
/// This is distinct from the legacy JSON TrainServiceAlerts records.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded protobuf file, whose decoding is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
pub fn encode_get_gtfs_real_time_train_service_alerts(
    input: GetGtfsRealTimeTrainServiceAlertsInput,
) -> Result<http::Request<Vec<u8>>, satay_runtime::Error> {
    let parts = get_gtfs_real_time_train_service_alerts_parts(input)?;
    satay_runtime::into_empty_request(parts)
}
pub fn decode_get_gtfs_real_time_train_service_alerts_response<B: AsRef<[u8]>>(
    response: satay_runtime::ResponseParts<B>,
) -> Result<GetGtfsRealTimeTrainServiceAlertsResponse, satay_runtime::Error> {
    let status = response.status;
    match status.as_u16() {
        200 => {
            let body = response.body;
            let value = satay_runtime::from_projected_json_slice::<Vec<String>>(
                body.as_ref(),
                "value",
                Some("link"),
            )?;
            Ok(GetGtfsRealTimeTrainServiceAlertsResponse::Ok(value))
        }
        _ => {
            let body = response.body;
            Ok(GetGtfsRealTimeTrainServiceAlertsResponse::UnexpectedStatus(
                status,
                body.as_ref().to_vec(),
            ))
        }
    }
}
