// @generated by satay. Do not edit by hand.
#![allow(
    clippy::doc_markdown,
    clippy::missing_errors_doc,
    clippy::must_use_candidate,
    clippy::needless_pass_by_value,
    clippy::return_self_not_must_use,
    clippy::single_match_else
)]

/// Returns a link to a protobuf file containing GTFS Realtime (Train Service Alerts) service alerts: unforeseen events affecting a station, route or the entire network.
/// This is distinct from the legacy JSON TrainServiceAlerts records.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded protobuf file, whose decoding is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
#[derive(Debug, Clone, PartialEq)]
pub struct GetGtfsRealTimeTrainServiceAlertsInput {}
impl GetGtfsRealTimeTrainServiceAlertsInput {
    pub fn new() -> Self {
        Self {}
    }
}
impl Default for GetGtfsRealTimeTrainServiceAlertsInput {
    fn default() -> Self {
        Self::new()
    }
}
/// Returns a link to a protobuf file containing GTFS Realtime (Train Service Alerts) service alerts: unforeseen events affecting a station, route or the entire network.
/// This is distinct from the legacy JSON TrainServiceAlerts records.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded protobuf file, whose decoding is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
#[derive(Debug, Clone, PartialEq)]
pub enum GetGtfsRealTimeTrainServiceAlertsResponse {
    /// Successful GTFS Realtime Train Service Alerts response.
    Ok(Vec<String>),
    UnexpectedStatus(http::StatusCode, Vec<u8>),
}
/// Returns a link to a protobuf file containing GTFS Realtime (Train Service Alerts) service alerts: unforeseen events affecting a station, route or the entire network.
/// This is distinct from the legacy JSON TrainServiceAlerts records.
/// The DataMall guide documents the field as `Link`; the live wire uses lowercase `link` with a `timestamp`.
/// Each pre-signed link expires after 15 minutes.
/// The API response is the link wrapper, not the downloaded protobuf file, whose decoding is outside this endpoint contract. See the General Transit Feed Specification documentation for the feed format.
///
/// **Update freq**: Ad-Hoc
pub fn get_gtfs_real_time_train_service_alerts_parts(
    _input: GetGtfsRealTimeTrainServiceAlertsInput,
) -> Result<satay_runtime::RequestParts<()>, satay_runtime::Error> {
    let mut uri = String::with_capacity(31);
    uri.push_str("/GTFSRealTimeTrainServiceAlerts");
    let headers = http::HeaderMap::new();
    Ok(satay_runtime::RequestParts {
        method: http::Method::GET,
        uri,
        headers,
        body: (),
    })
}
